// Seed catalog: fictional developers and games. Only `voidrunner` and `tidewater`
// ship real builds; released placeholder titles launch a shared placeholder build
// so the full buy → library → play flow works for every released game.

export const developers = [
  { id: 'dev_moonwhisker', name: 'Moonwhisker Studio', location: 'Lisbon, PT' },
  { id: 'dev_ninefold', name: 'Ninefold', location: 'Tallinn, EE' },
  { id: 'dev_lowtide', name: 'Low Tide Studio', location: 'Porto, PT' },
  { id: 'dev_kestrel', name: 'Kestrel & Moth', location: 'Bristol, UK' },
  { id: 'dev_paperlight', name: 'Paperlight Games', location: 'Kyoto, JP' },
  { id: 'dev_orbitaltea', name: 'Orbital Tea', location: 'Montréal, CA' },
  { id: 'dev_ashgrove', name: 'Ashgrove', location: 'Tbilisi, GE' },
  { id: 'dev_glasshouse', name: 'Glasshouse Collective', location: 'Berlin, DE' },
  { id: 'dev_smallhours', name: 'Small Hours Studio', location: 'Portland, US' },
  { id: 'dev_northbound', name: 'Northbound Interactive', location: 'Oslo, NO' },
];

const P = {
  synth: { sky1: '#0a0420', sky2: '#3b0a45', far: '#1a0630', near: '#07020f', fog: '#ff4fd8', accent: '#ff3fa4', accent2: '#23e6ff' },
  harbor: { sky1: '#0d1b2a', sky2: '#c46a3f', far: '#233447', near: '#0a1220', fog: '#f2a65a', accent: '#ffc46b', accent2: '#8fd3e8' },
  hollow: { sky1: '#07090c', sky2: '#141b22', far: '#10161c', near: '#1f2a33', fog: '#6ea3b5', accent: '#ffb347', accent2: '#79e3ff' },
  glass: { sky1: '#050b18', sky2: '#0f2340', far: '#0b1a30', near: '#030811', fog: '#7ab8ff', accent: '#8ee7ff', accent2: '#c59bff' },
  kepler: { sky1: '#02030a', sky2: '#0b1030', far: '#0b1030', near: '#020309', fog: '#ffffff', accent: '#ffa45c', accent2: '#6fb7ff' },
  ash: { sky1: '#1c0d08', sky2: '#8a3b16', far: '#4a2210', near: '#120804', fog: '#ffb07a', accent: '#ffd08a', accent2: '#ff5a2a' },
  neon: { sky1: '#050612', sky2: '#1a0f33', far: '#161233', near: '#07060f', fog: '#8a5cff', accent: '#ffd23f', accent2: '#ff2e88' },
  pine: { sky1: '#05080a', sky2: '#16262a', far: '#122025', near: '#030506', fog: '#8fb3b0', accent: '#ffcf87', accent2: '#e9ffa8' },
  summit: { sky1: '#0c1a33', sky2: '#9fb6d6', far: '#5a7196', near: '#0e1628', fog: '#ffffff', accent: '#fff2d6', accent2: '#9fd8ff' },
  hearth: { sky1: '#1b2a3a', sky2: '#e0975a', far: '#3f5a3a', near: '#132016', fog: '#ffd9a0', accent: '#ffe08a', accent2: '#b6f07a' },
  star: { sky1: '#010208', sky2: '#12072b', far: '#12072b', near: '#010105', fog: '#ffffff', accent: '#9ff0ff', accent2: '#ff9ff3' },
  undertow: { sky1: '#01060a', sky2: '#062733', far: '#06222c', near: '#010407', fog: '#2fa3b8', accent: '#5ff5d8', accent2: '#1f7d95' },
  glyph: { sky1: '#0d0716', sky2: '#2a1240', far: '#1a0d2a', near: '#07040c', fog: '#b08cff', accent: '#ffc86b', accent2: '#b08cff' },
  ironbark: { sky1: '#141007', sky2: '#6b5a2a', far: '#3d341a', near: '#0f0c05', fog: '#e8d49a', accent: '#ffe7a3', accent2: '#e0602f' },
  orbit: { sky1: '#021008', sky2: '#08361f', far: '#0a2a18', near: '#020a05', fog: '#4dff9a', accent: '#b6ff4d', accent2: '#4dffc3' },
};

export const games = [
  {
    id: 'nightpaw', title: 'Nightpaw', developerId: 'dev_moonwhisker', priceCents: 999,
    tags: ['Metroidvania', 'Action', 'Dark Fantasy', 'Cute', 'Exploration', 'Platformer'],
    motif: 'dungeon', catArt: true, hud: 'action',
    palette: { sky1: '#07070d', sky2: '#15132a', far: '#100e1c', near: '#221d33', fog: '#8f86c9', accent: '#ffb347', accent2: '#c7b8ff' },
    logo: { font: 'Cinzel', weight: 700, color: '#f1e9d6', glow: '#8f86c9', case: 'upper', spacing: '.18em' },
    short: 'A small black cat in a red scarf-cloak follows a missing girl down the old well, into the Underneath, where lost things go.',
    description: [
      'One stormy night Mira follows a pale moth out of her window, and in the morning her bed is empty. Her cat, Nightpaw, has already spent eight of his nine lives. He jumps down the well anyway.',
      'The Underneath used to be lit by the Hearthlamp. Now it is dark, and lost things are forgetting what they were: thimbles, socks and buttons gone hollow. Scratch your way through them, find the Shadow Dash and Moth Wings, and recover the lost lives you left down here long ago.',
      'A story-driven metroidvania with painted storybook cutscenes, a cast of polite, frightened creatures, secrets, and the Hollow Warden waiting in his hall. Keyboard, gamepad and touch.',
    ],
    features: ['Single-player', 'Cloud Saves', 'Achievements', 'Controller Support', 'Touch Controls', 'Instant Play'],
    releaseDate: '2026-09-24', status: 'released', rating: { pct: 97, count: 1873 }, stats: { sales: 36400, trend: 100 },
    featured: true, demo: { minutes: 5 }, package: { dir: 'nightpaw', version: '2.0.0' },
    blurb: 'Cat-sized metroidvania',
  },
  {
    id: 'voidrunner', title: 'Voidrunner', developerId: 'dev_ninefold', priceCents: 499,
    tags: ['Arcade', 'Shoot \'em Up', 'Retro', 'Score Attack', 'Fast-Paced'],
    motif: 'synth', palette: P.synth, hud: 'action', logo: { font: 'Orbitron', weight: 900, color: '#ff5fb7', glow: '#23e6ff', case: 'upper', spacing: '.12em' },
    short: 'A neon arcade shooter about surviving the space between signals. Thread bullet storms, chain kills, and push deeper into the void one sector at a time.',
    description: [
      'Voidrunner is a tight, one-more-run arcade shooter built for short sessions and long obsessions. Pilot a courier ship through collapsing sectors of dead space, where every wave is faster, meaner and louder than the last.',
      'Your furthest sector is remembered. Pick up where you left off, or start from Sector 1 and chase a clean high score. Every run feeds your personal best, synced to your Lantern account.',
      'Built entirely on the web platform, Voidrunner launches in under a second, with no installer and no loading screens.',
    ],
    features: ['Single-player', 'Cloud Saves', 'Achievements', 'Keyboard & Mouse', 'Touch Controls', 'Instant Play'],
    releaseDate: '2026-09-10', status: 'released', rating: { pct: 94, count: 2318 }, stats: { sales: 41200, trend: 98 },
    featured: true, demo: { minutes: 3 }, package: { dir: 'voidrunner', version: '1.0.0' },
    blurb: 'Neon arcade shooter · runs in 1s',
  },
  {
    id: 'tidewater', title: 'Tidewater Trading Co.', developerId: 'dev_lowtide', priceCents: 799,
    tags: ['Incremental', 'Management', 'Cozy', 'Idle', 'Relaxing'],
    motif: 'sea', palette: P.harbor, hud: 'strategy', logo: { font: 'Playfair Display', weight: 700, style: 'italic', color: '#ffe3b0', case: 'none', spacing: '0' },
    short: 'Build a sleepy fishing village into the greatest trading harbor on the coast. Buy boats, raise a lighthouse, and let the tide work for you, even while you are away.',
    description: [
      'You inherit one rowboat, one net and a harbor nobody visits. Haul in the morning catch, buy your first skiff, and watch a quiet cove turn into a thriving port.',
      'Tidewater is a gentle incremental management game. Your fleet keeps working while you are gone, and the harbor you leave is exactly the harbor you come back to, down to the last coin.',
      'Progress is saved automatically through Lantern Cloud Saves.',
    ],
    features: ['Single-player', 'Cloud Saves', 'Offline Progress', 'Achievements', 'Mouse & Touch', 'Instant Play'],
    releaseDate: '2026-08-21', status: 'released', rating: { pct: 91, count: 1564 }, stats: { sales: 28900, trend: 91 },
    featured: true, demo: { minutes: 5 }, package: { dir: 'tidewater', version: '1.2.0' },
    blurb: 'Cozy harbor-building idle game',
  },
  {
    id: 'hollow-lantern', title: 'The Hollow Lantern', developerId: 'dev_kestrel', priceCents: 1499,
    tags: ['Metroidvania', 'Dark Fantasy', 'Exploration', 'Atmospheric', 'Souls-like'],
    motif: 'dungeon', palette: P.hollow, hud: 'rpg', logo: { font: 'Cinzel', weight: 700, color: '#f3dcae', case: 'upper', spacing: '.08em' },
    short: 'Descend into a drowned cathedral carrying the last light in the world. A hand-drawn metroidvania about what we keep burning, and why.',
    description: [
      'Beneath the city of Vell lies a cathedral that swallowed its own congregation. You are the lamplighter sent to relight it — armed with a lantern that burns memories as fuel.',
      'Explore an interconnected underworld of flooded naves, bone archives and bell towers. Every shortcut you open changes how the world fits together.',
    ],
    features: ['Single-player', 'Cloud Saves', 'Achievements', 'Controller Support'],
    releaseDate: '2026-06-04', status: 'released', rating: { pct: 96, count: 9412 }, stats: { sales: 120400, trend: 72 },
    featured: true, demo: null, package: null, blurb: 'Hand-drawn metroidvania',
  },
  {
    id: 'driftglass', title: 'Driftglass', developerId: 'dev_paperlight', priceCents: 999,
    tags: ['Puzzle', 'Minimalist', 'Relaxing', 'Atmospheric'],
    motif: 'crystal', palette: P.glass, hud: 'puzzle', logo: { font: 'Space Grotesk', weight: 500, color: '#c9f3ff', case: 'lower', spacing: '.3em' },
    short: 'Bend light through a cavern of living glass. 180 hand-crafted refraction puzzles with no timers, no text and no hurry.',
    description: [
      'Driftglass is a quiet puzzle game about light. Rotate, split and tint beams through crystal caverns until the whole cave sings.',
      'Each chapter introduces one new idea and explores it completely. Designed to be played in ten-minute sittings.',
    ],
    features: ['Single-player', 'Cloud Saves', 'Achievements', 'Mouse & Touch'],
    releaseDate: '2026-07-15', status: 'released', rating: { pct: 89, count: 3120 }, stats: { sales: 38100, trend: 64 },
    featured: false, demo: null, package: null, blurb: 'Serene refraction puzzler',
  },
  {
    id: 'kepler', title: 'Last Light of Kepler', developerId: 'dev_orbitaltea', priceCents: 999,
    tags: ['Strategy', 'Space', 'Turn-Based', 'Sci-fi', '4X'],
    motif: 'space', palette: P.kepler, hud: 'strategy', logo: { font: 'Rajdhani', weight: 700, color: '#ffd7b0', case: 'upper', spacing: '.22em' },
    short: 'A compact 4X about the final colony fleet. Settle, bargain and endure across a dying star system in 90-minute campaigns.',
    description: [
      'Kepler-442 is going dark. Lead the last colony fleet across a collapsing system, trading with rival arks and deciding who gets to see the next century.',
      'Every campaign fits in an evening. Every decision stays on the record.',
    ],
    features: ['Single-player', 'Cloud Saves', 'Achievements'],
    releaseDate: '2026-05-02', status: 'released', rating: { pct: 87, count: 4820 }, stats: { sales: 64000, trend: 55 },
    featured: true, demo: null, package: null, blurb: 'Evening-sized space 4X',
  },
  {
    id: 'ashfall', title: 'Ashfall', developerId: 'dev_ashgrove', priceCents: 799,
    tags: ['Survival', 'Roguelite', 'Post-Apocalyptic', 'Crafting'],
    motif: 'desert', palette: P.ash, hud: 'action', logo: { font: 'Bebas Neue', weight: 400, color: '#ffd6a8', case: 'upper', spacing: '.18em' },
    short: 'The sky has been burning for eleven years. Scavenge, craft and cross the ash wastes in a survival roguelite where every expedition rewrites the map.',
    description: [
      'Ashfall drops you into a scorched, procedurally-shifting wasteland with a backpack, a water filter and a rumour of green land to the north.',
      'Die, and the world remembers: your old camps, your caches, your mistakes.',
    ],
    features: ['Single-player', 'Cloud Saves', 'Achievements', 'Controller Support'],
    releaseDate: '2026-09-01', status: 'released', rating: { pct: 82, count: 1204 }, stats: { sales: 22000, trend: 88 },
    featured: false, demo: null, package: null, blurb: 'Survival roguelite',
  },
  {
    id: 'night-market', title: 'Night Market 2089', developerId: 'dev_glasshouse', priceCents: 999,
    tags: ['Cyberpunk', 'Narrative', 'Detective', 'Choices Matter'],
    motif: 'city', palette: P.neon, hud: 'rpg', logo: { font: 'Orbitron', weight: 700, color: '#ffe066', glow: '#ff2e88', case: 'upper', spacing: '.1em' },
    short: 'A noodle stand, a missing courier, and a city that never switches off. A branching detective story told one customer at a time.',
    description: [
      'Run a noodle stall in the rain-soaked lower city while quietly investigating the disappearance of your best friend. Every customer has a story — and some of them are lying.',
      'Over 40 characters, 11 endings, and a soundtrack by the synth trio Low Orbit.',
    ],
    features: ['Single-player', 'Cloud Saves', 'Achievements'],
    releaseDate: '2026-08-02', status: 'released', rating: { pct: 93, count: 5410 }, stats: { sales: 57000, trend: 79 },
    featured: true, demo: null, package: null, blurb: 'Cyberpunk detective story',
  },
  {
    id: 'pinewatch', title: 'Pinewatch', developerId: 'dev_smallhours', priceCents: 499,
    tags: ['Horror', 'Short', 'Atmospheric', 'Walking Sim'],
    motif: 'forest', palette: P.pine, hud: 'rpg', logo: { font: 'Playfair Display', weight: 700, color: '#f2e6c9', case: 'none', spacing: '.02em' },
    short: 'Seven nights in a fire lookout tower. Something in the treeline is keeping a schedule. A 90-minute horror story best played with headphones.',
    description: [
      'You took the lookout job to be alone. The radio says otherwise.',
      'Pinewatch is a short, dense horror experience with no jump scares — just the forest, the dark, and a growing sense that you are being watched from the trees.',
    ],
    features: ['Single-player', 'Cloud Saves', 'Achievements'],
    releaseDate: '2026-07-30', status: 'released', rating: { pct: 90, count: 2210 }, stats: { sales: 30500, trend: 60 },
    featured: false, demo: null, package: null, blurb: 'Short lookout-tower horror',
  },
  {
    id: 'cold-summit', title: 'Cold Summit', developerId: 'dev_northbound', priceCents: 299,
    tags: ['Platformer', 'Precision', 'Difficult', 'Pixel Art'],
    motif: 'mountains', palette: P.summit, hud: 'action', logo: { font: 'Bebas Neue', weight: 400, color: '#ffffff', case: 'upper', spacing: '.3em' },
    short: 'One mountain. One rope. 600 screens of precision climbing between you and the summit.',
    description: [
      'Cold Summit is a brutally fair precision platformer. Swing, grip and wall-jump up a frozen peak where every screen is a puzzle of timing.',
      'Instant respawns, speedrun timer built in.',
    ],
    features: ['Single-player', 'Cloud Saves', 'Achievements', 'Controller Support'],
    releaseDate: '2026-04-11', status: 'released', rating: { pct: 95, count: 6890 }, stats: { sales: 88000, trend: 40 },
    featured: false, demo: null, package: null, blurb: 'Precision climbing platformer',
  },
  {
    id: 'hearthfield', title: 'Hearthfield', developerId: 'dev_lowtide', priceCents: 1499,
    tags: ['Farming', 'Cozy', 'Life Sim', 'Crafting', 'Relaxing'],
    motif: 'mountains', palette: P.hearth, hud: 'strategy', logo: { font: 'Playfair Display', weight: 700, color: '#fff1cf', case: 'none', spacing: '0' },
    short: 'Restore your grandmother\'s valley farm, one season at a time. Plant, forage, cook and slowly become part of a village that remembers her.',
    description: [
      'Hearthfield is a farming life sim with a long memory. The valley changes with the seasons — and with you.',
      'Grow 60 crops, cook over 100 recipes, and uncover the story of the woman who built the farm.',
    ],
    features: ['Single-player', 'Cloud Saves', 'Achievements', 'Controller Support'],
    releaseDate: '2026-03-19', status: 'released', rating: { pct: 92, count: 11020 }, stats: { sales: 142000, trend: 50 },
    featured: false, demo: null, package: null, blurb: 'Valley farming life sim',
  },
  {
    id: 'ironbark', title: 'Ironbark Tactics', developerId: 'dev_northbound', priceCents: 1499,
    tags: ['Tactics', 'Turn-Based', 'Strategy', 'Fantasy'],
    motif: 'desert', palette: P.ironbark, hud: 'strategy', logo: { font: 'Cinzel', weight: 700, color: '#ffe7a3', case: 'upper', spacing: '.12em' },
    short: 'Command a mercenary company across a dry frontier in grid-based tactics where terrain, weather and loyalty all matter.',
    description: [
      'Hire, train and lose soldiers in a campaign where the map fights back. Sandstorms blind archers; flash floods split your line.',
      'Your company\'s history is permanent — every veteran has a story.',
    ],
    features: ['Single-player', 'Cloud Saves', 'Achievements'],
    releaseDate: '2026-09-18', status: 'released', rating: { pct: 85, count: 640 }, stats: { sales: 9800, trend: 83 },
    featured: false, demo: null, package: null, blurb: 'Frontier grid tactics',
  },
  {
    id: 'pocket-orbit', title: 'Pocket Orbit', developerId: 'dev_orbitaltea', priceCents: 299,
    tags: ['Arcade', 'Casual', 'Minimalist', 'Score Attack'],
    motif: 'synth', palette: P.orbit, hud: 'puzzle', logo: { font: 'Press Start 2P', weight: 400, color: '#b6ff4d', case: 'upper', spacing: '.05em' },
    short: 'Slingshot a tiny satellite around tiny planets. One-thumb physics arcade with daily challenge seeds.',
    description: [
      'Pocket Orbit is a one-button gravity toy with a very high skill ceiling. Every day brings a new seeded challenge.',
    ],
    features: ['Single-player', 'Cloud Saves', 'Achievements', 'Touch Controls'],
    releaseDate: '2026-09-22', status: 'released', rating: { pct: 88, count: 212 }, stats: { sales: 4100, trend: 86 },
    featured: false, demo: null, package: null, blurb: 'One-thumb gravity arcade',
  },
  {
    id: 'starfall', title: 'Starfall Cartographers', developerId: 'dev_orbitaltea', priceCents: 1499,
    tags: ['Exploration', 'Space', 'Co-op Planned', 'Sci-fi'],
    motif: 'space', palette: P.star, hud: 'strategy', logo: { font: 'Rajdhani', weight: 700, color: '#d8fbff', case: 'upper', spacing: '.3em' },
    short: 'Chart a galaxy that is still being born. Hand-map nebulae, name new stars and sell your charts to the highest bidder.',
    description: ['Starfall Cartographers is an exploration game about making maps of places nobody has seen. Coming soon to Lantern.'],
    features: ['Single-player', 'Cloud Saves', 'Achievements'],
    releaseDate: '2026-11-14', status: 'coming_soon', rating: null, stats: { sales: 0, trend: 77 },
    featured: false, demo: null, package: null, blurb: 'Coming November 14',
  },
  {
    id: 'undertow', title: 'Undertow', developerId: 'dev_smallhours', priceCents: 999,
    tags: ['Horror', 'Underwater', 'Atmospheric', 'Survival'],
    motif: 'sea', palette: P.undertow, hud: 'action', logo: { font: 'Cinzel', weight: 700, color: '#aefcea', case: 'upper', spacing: '.35em' },
    short: 'A deep-sea salvage job goes quiet at 4,000 metres. From the makers of Pinewatch.',
    description: ['Undertow is a claustrophobic survival horror set aboard a failing deep-sea salvage rig. Coming early 2027.'],
    features: ['Single-player', 'Cloud Saves', 'Achievements'],
    releaseDate: '2027-02-12', status: 'coming_soon', rating: null, stats: { sales: 0, trend: 70 },
    featured: false, demo: null, package: null, blurb: 'Coming 2027',
  },
  {
    id: 'glyphbound', title: 'Glyphbound', developerId: 'dev_paperlight', priceCents: 1199,
    tags: ['Deckbuilder', 'Roguelike', 'Strategy', 'Fantasy'],
    motif: 'crystal', palette: P.glyph, hud: 'puzzle', logo: { font: 'Cinzel', weight: 700, color: '#ffd89a', case: 'upper', spacing: '.16em' },
    short: 'A roguelike deckbuilder where your cards are spoken words — and combining them writes new spells.',
    description: ['Glyphbound lets you chain glyphs into sentences that become spells. Coming October 30.'],
    features: ['Single-player', 'Cloud Saves', 'Achievements'],
    releaseDate: '2026-10-30', status: 'coming_soon', rating: null, stats: { sales: 0, trend: 81 },
    featured: false, demo: null, package: null, blurb: 'Coming October 30',
  },
];

// Placeholder achievements for titles without real builds.
export const placeholderAchievements = [
  { id: 'first_steps', name: 'First Steps', description: 'Launch the game for the first time.' },
  { id: 'regular', name: 'Regular', description: 'Launch the game 3 times.' },
  { id: 'dedicated', name: 'Dedicated', description: 'Launch the game 10 times.' },
];
